version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
    volumes:
      - .:/frontend
    ports:
      - 3006:3006
      - 3000:3000

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
  db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: amsohio_postgres
    volumes:
      - kapoorsoftwaresolutions_postgres_data:/var/lib/postgresql/data:Z
      - kapoorsoftwaresolutions_postgres_data_backups:/backups:z
    ports:
      - 5432:5432
    env_file:
      - ./.env

  redis:
    image: redis:latest

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: kapoorsoftwaresolutions_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: kapoorsoftwaresolutions_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: kapoorsoftwaresolutions_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  kapoorsoftwaresolutions_postgres_data:
  static_volume:
  kapoorsoftwaresolutions_postgres_data_backups: